/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.Aircraft;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alekh
 */
public class TravelAgencyMngWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgencyMngWorkAreaJPanel
     */
    private JPanel cardSequenceJPanel;
    private TravelAgency travelAgency;
    private Aircraft airliner;
    public TravelAgencyMngWorkAreaJPanel(JPanel cardSequenceJpanel, TravelAgency travelAgency) {
        initComponents();
        this.cardSequenceJPanel= cardSequenceJpanel;
        this.travelAgency = travelAgency;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateTable() {
    DefaultTableModel dtm = (DefaultTableModel)tbltravelagency.getModel();
        dtm.setRowCount(0);
        for(Aircraft airliner:travelAgency.getAirlinerDirectory().getAirlinerList()) {
            int i=0;
            int count = 0;
            for(Flight flight:airliner.getFlightList()) {
            
            if(airliner.getAirlinerName().equals(flight.getAirlinerName())){
            Object[] row = new Object[8];
            row[0]=airliner.getAirlinerName();
            row[1]=flight;
            row[2]=airliner.getFlightList().get(i).getSource();
            row[3]=airliner.getFlightList().get(i).getDestination();
            row[4]=airliner.getFlightList().get(i).getDepartureTime();
            row[5]=airliner.getFlightList().get(i).getArrivalTime();
            row[6]=airliner.getFlightList().get(i).getFlightPrice();
            row[7]=airliner.getFlightList().get(i).getTotalSeats();
            dtm.addRow(row);
            count++;
            }
            i++;
            }
            airliner.setAirlinerFleetSize(count);
        }
            
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltravelagency = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnDeleteFlight = new javax.swing.JButton();
        btnViewFlightDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE TRAVEL AGENCY");

        txtSource.setBackground(new java.awt.Color(245, 245, 246));
        txtSource.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtSource.setForeground(new java.awt.Color(78, 114, 175));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Destination :");

        txtDestination.setBackground(new java.awt.Color(245, 245, 246));
        txtDestination.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtDestination.setForeground(new java.awt.Color(78, 114, 175));

        tbltravelagency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Flight Number", "Source", "Destination", "Departure time", "Arrival Time", "Price", "Total Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbltravelagency);
        if (tbltravelagency.getColumnModel().getColumnCount() > 0) {
            tbltravelagency.getColumnModel().getColumn(0).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(1).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(2).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(3).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(4).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(5).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(6).setResizable(false);
            tbltravelagency.getColumnModel().getColumn(7).setResizable(false);
        }

        btnSearch.setBackground(new java.awt.Color(245, 245, 246));
        btnSearch.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(78, 114, 175));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDeleteFlight.setBackground(new java.awt.Color(245, 245, 246));
        btnDeleteFlight.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDeleteFlight.setForeground(new java.awt.Color(78, 114, 175));
        btnDeleteFlight.setText("Delete Flight");
        btnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightActionPerformed(evt);
            }
        });

        btnViewFlightDetails.setBackground(new java.awt.Color(245, 245, 246));
        btnViewFlightDetails.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnViewFlightDetails.setForeground(new java.awt.Color(78, 114, 175));
        btnViewFlightDetails.setText("View Flight Details");
        btnViewFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if((txtSource.getText() != null)&& !(txtSource.getText().isEmpty())
           && (txtDestination.getText() != null)&& !(txtDestination.getText().isEmpty()) 
            )
       {
           
       try{
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
            Matcher m = pattern.matcher(txtSource.getText() + txtDestination.getText());
            boolean boo = m.find();
        if(boo == true || source == null || destination == null ) {
            JOptionPane.showMessageDialog(null,"Please remove special character from text field");
        }
        else{
         DefaultTableModel dtm = (DefaultTableModel)tbltravelagency.getModel();
         dtm.setRowCount(0);
        for(Aircraft airliner: travelAgency.getAirlinerDirectory().getAirlinerList()) {
            for(Flight flight:airliner.getFlightList()) {
                if(flight.getSource().equalsIgnoreCase(source)&&flight.getDestination().equalsIgnoreCase(destination)){
                    
                  if(airliner.getAirlinerName().equals(flight.getAirlinerName())){
                    Object[] row = new Object[8];
                    row[0]=airliner.getAirlinerName();
                    row[1]=flight;
                    row[2]=flight.getSource();
                    row[3]=flight.getDestination();
                    row[4]=flight.getDepartureTime();
                    row[5]=flight.getArrivalTime();
                    row[6]=flight.getFlightPrice();
                    row[7]=flight.getTotalSeats();
                    dtm.addRow(row);
                  }
                }
            }
        }
        }}catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Please Enter Numeric Values ");
        }
       }
      else{
        JOptionPane.showMessageDialog(null,"Please enter both source and destination to search ");

    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbltravelagency.getSelectedRow();
        if(selectedRow  >= 0) {
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the airliner details ?","Warning",dialogButton);
           if(dialogResult == JOptionPane.YES_OPTION) {
               Flight flight = (Flight)tbltravelagency.getValueAt(selectedRow,1);
               for(Aircraft airliner:travelAgency.getAirlinerDirectory().getAirlinerList()){
                   airliner.deleteFlight(flight);
               } 
               populateTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteFlightActionPerformed

    private void btnViewFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbltravelagency.getSelectedRow();
         if(selectedRow<0) {
                  JOptionPane.showMessageDialog(null, "Please select a row from table first to view flight details","Warning",JOptionPane.WARNING_MESSAGE);

         }
         else {
           Flight flight = (Flight)tbltravelagency.getValueAt(selectedRow,1);
           ViewFlightJpanel panel = new ViewFlightJpanel(cardSequenceJPanel,flight);
           cardSequenceJPanel.add("ViewFlightJpanel",panel);
           CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
           layout.next(cardSequenceJPanel);
         }
    }//GEN-LAST:event_btnViewFlightDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewFlightDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltravelagency;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
